# Font
font_family Iosevka
font_size   12

# Cursor
cursor_trail 1
cursor_shape block

# Terminal bell
enable_audio_bell no

# Window layout
remember_window_size no

# Color scheme
foreground #dddddd
background #181818

