# Font
font_family      Iosevka
bold_font        Iosevka Bold
italic_font      Iosevka Oblique
bold_italic_font Iosevka Bold Oblique
font_size        12

# Cursor
cursor_trail 1
cursor_shape block

# Terminal bell
enable_audio_bell no

# Window layout
remember_window_size no

# Color scheme
foreground #dddddd
background #181818

# Other
allow_remote_control no
watch_files no

# Colors

# -- black
color0 #000000
color8 #767676

# -- red
color1 #cc3434
color9 #eb4e4e

# -- green
color2  #5ec25e
color10 #52fd52

# -- yellow
color3  #ccca4e
color11 #fffe63

# -- blue
color4  #418bcc
color12 #69b5ff

# -- magenta
color5  #d154d1
color13 #ff75ff

# -- cyan
color6  #47c9c9
color14 #77fcfc

# -- white
color7  #dddddd
color15 #ffffff


