# Font
font_family      Iosevka
bold_font        Iosevka Bold
italic_font      Iosevka Oblique
bold_italic_font Iosevka Bold Oblique
font_size        12

# Cursor
cursor_trail 1
cursor_shape block

# Terminal bell
enable_audio_bell no

# Window layout
remember_window_size no

# Color scheme
foreground #dddddd
background #181818

# Other
allow_remote_control no
watch_files no
